services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-management-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=postgresql://lms_kuuo_user:9SHBC4OHLC2jVz0HRbFzqoqfhjU30TJ4@dpg-d4nsli9r0fns73dirvf0-a/lms_kuuo
    volumes:
      # Persist database
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - library-network

networks:
  library-network:
    driver: bridge