export const booksData = {
  academic: [
    {
      bookid: 1,
      title: "Principles of Programming Languages",
      author: "Robert W. Sebesta",
      publishedYear: "2020",
      publisher: "Pearson",
      availableCopy: 4,
      rarity: "Common",
      genre: ["Computer Science", "Programming"],
      description:
        "Covers fundamental programming paradigms, syntax, and semantics of modern languages.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 2,
      title: "Computer Architecture",
      author: "John L. Hennessy",
      publishedYear: "2018",
      publisher: "Morgan Kaufmann",
      availableCopy: 3,
      rarity: "Rare",
      genre: ["Hardware", "Systems"],
      description:
        "Comprehensive guide to the design and analysis of modern computer architecture.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 3,
      title: "Probability & Statistics",
      author: "Jay L. Devore",
      publishedYear: "2019",
      publisher: "Cengage Learning",
      availableCopy: 5,
      rarity: "Common",
      genre: ["Mathematics", "Statistics"],
      description:
        "Introduces statistical concepts with practical engineering applications.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 4,
      title: "Data Structures & Algorithms",
      author: "Mark Allen Weiss",
      publishedYear: "2021",
      publisher: "Pearson",
      availableCopy: 6,
      rarity: "Common",
      genre: ["Computer Science", "Algorithms"],
      description:
        "Detailed explanation of data structures and algorithm analysis in Java.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 5,
      title: "Operating Systems",
      author: "Abraham Silberschatz",
      publishedYear: "2022",
      publisher: "Wiley",
      availableCopy: 4,
      rarity: "Uncommon",
      genre: ["Systems", "Software Engineering"],
      description:
        "Explores the principles and design of modern operating systems.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
  ],

  general: [
    {
      bookid: 6,
      title: "1984",
      author: "George Orwell",
      publishedYear: "1949",
      publisher: "Secker & Warburg",
      availableCopy: 2,
      rarity: "Rare",
      genre: ["Dystopian", "Classic"],
      description:
        "A chilling vision of totalitarianism and the power of surveillance.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 7,
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      publishedYear: "1960",
      publisher: "J.B. Lippincott & Co.",
      availableCopy: 3,
      rarity: "Common",
      genre: ["Fiction", "Social Justice"],
      description:
        "A timeless story of racial injustice and childhood in the Deep South.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 8,
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      publishedYear: "1925",
      publisher: "Charles Scribner’s Sons",
      availableCopy: 2,
      rarity: "Rare",
      genre: ["Classic", "Novel"],
      description:
        "A critique of the American Dream through the eyes of Jay Gatsby.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 9,
      title: "Pride and Prejudice",
      author: "Jane Austen",
      publishedYear: "1813",
      publisher: "T. Egerton",
      availableCopy: 4,
      rarity: "Uncommon",
      genre: ["Romance", "Classic"],
      description:
        "The romantic clash between Elizabeth Bennet and Mr. Darcy.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 10,
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      publishedYear: "1951",
      publisher: "Little, Brown and Company",
      availableCopy: 5,
      rarity: "Common",
      genre: ["Fiction", "Coming of Age"],
      description:
        "Holden Caulfield’s story of teenage rebellion and isolation.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
  ],

  research: [
    {
      bookid: 11,
      title: "Computing Machinery and Intelligence",
      author: "Alan Turing",
      publishedYear: "1950",
      publisher: "Mind Journal",
      availableCopy: 1,
      rarity: "Rare",
      genre: ["Artificial Intelligence", "Philosophy"],
      description: "The landmark paper proposing the concept of the Turing Test.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 12,
      title: "The Mathematical Theory of Communication",
      author: "Claude E. Shannon",
      publishedYear: "1948",
      publisher: "Bell System Technical Journal",
      availableCopy: 1,
      rarity: "Rare",
      genre: ["Information Theory", "Mathematics"],
      description:
        "Defines the quantitative measure of information and communication systems.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 13,
      title: "Ideas That Created the Future",
      author: "Harry R. Lewis",
      publishedYear: "2021",
      publisher: "MIT Press",
      availableCopy: 3,
      rarity: "Common",
      genre: ["Computer Science", "History"],
      description:
        "Collection of classic papers that shaped the field of computer science.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 14,
      title: "The Art of Computer Programming, Vol. 1",
      author: "Donald E. Knuth",
      publishedYear: "2011",
      publisher: "Addison-Wesley",
      availableCopy: 2,
      rarity: "Rare",
      genre: ["Algorithms", "Mathematics"],
      description:
        "Seminal reference for algorithms and computational theory.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 15,
      title: "On Computable Numbers",
      author: "Alan Turing",
      publishedYear: "1936",
      publisher: "Proceedings of the London Mathematical Society",
      availableCopy: 1,
      rarity: "Very Rare",
      genre: ["Mathematics", "Computation"],
      description:
        "Introduced the concept of a Turing machine, foundational to computer science.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
  ],

  science: [
    {
      bookid: 16,
      title: "Fundamentals of Electrical Engineering",
      author: "Rajesh Singh",
      publishedYear: "2020",
      publisher: "Cambridge University Press",
      availableCopy: 4,
      rarity: "Common",
      genre: ["Electrical Engineering"],
      description: "Comprehensive introduction to electrical systems and circuits.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 17,
      title: "Mechanical Engineering Design",
      author: "Joseph E. Shigley",
      publishedYear: "2015",
      publisher: "McGraw-Hill Education",
      availableCopy: 5,
      rarity: "Common",
      genre: ["Mechanical Engineering"],
      description:
        "Covers key mechanical design principles and stress analysis.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 18,
      title: "Civil Engineering Materials",
      author: "Shan Somayaji",
      publishedYear: "2012",
      publisher: "Pearson",
      availableCopy: 3,
      rarity: "Uncommon",
      genre: ["Civil Engineering"],
      description:
        "Focuses on the properties and behavior of materials in civil construction.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 19,
      title: "Introduction to Chemical Engineering",
      author: "David M. Himmelblau",
      publishedYear: "2019",
      publisher: "Pearson",
      availableCopy: 2,
      rarity: "Rare",
      genre: ["Chemical Engineering"],
      description:
        "Introduction to mass transfer, thermodynamics, and chemical reaction design.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
    {
      bookid: 20,
      title: "Biotechnology for Beginners",
      author: "Reinhard Renneberg",
      publishedYear: "2017",
      publisher: "Academic Press",
      availableCopy: 5,
      rarity: "Common",
      genre: ["Biotechnology"],
      description:
        "An accessible guide to modern biotechnology applications.",
      image: "https://randomuser.me/api/portraits/men/77.jpg",
    },
  ],
};

export const allBooks = Object.values(booksData).flat();
